// export const NET_ITEMS_REQUEST = 'NET_ITEMS_REQUEST'
// // export const NET_ITEMS_SUCCESS_PAGE_FIRST = 'NET_ITEMS_SUCCESS_PAGE_FIRST'
// // export const NET_ITEMS_SUCCESS_END = 'NET_ITEMS_SUCCESS_END'

// export const NET_ITEMS_FAILURE = 'NET_ITEMS_FAILURE'

// export const NET_TYPES_REQUEST = 'NET_TYPES_REQUEST'
// export const NET_TYPES_SUCCESS = 'NET_TYPES_SUCCESS'
// export const NET_TYPES_FAILURE = 'NET_TYPES_FAILURE'

// export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
// export const SET_FILTER_SUBSTR = 'SET_FILTER_SUBSTR'
// export const SET_FILTER_TYPES = 'SET_FILTER_TYPES'

export const SET_FILTER = 'SET_FILTER'
export const SET_FILTER_END = 'SET_FILTER_END'

export const SET_PAGE = 'SET_PAGE'
export const SET_PAGE_SUCCESS_BATCH = 'SET_PAGE_SUCCESS_BATCH'

export const SET_ENTITIES = 'SET_ENTITIES'

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE'

export const SET_ERROR = 'SET_ERROR'
export const SET_TYPELIST = 'SET_TYPELIST'
