
export const CHANGE_FILTER = 'CHANGE_FILTER'

export const SELECTION_SUCCES_BATCH = 'SELECTION_SUCCES_BATCH'
export const SELECTION_CONTINUE = 'SELECTION_CONTINUE'

export const SET_PAGE = 'SET_PAGE'
export const SET_PAGE_SUCCESS_BATCH = 'SET_PAGE_SUCCESS_BATCH'
// export const SET_PAGE_FAILURE = 'SET_PAGE_FAILURE'

export const SET_TYPELIST = 'SET_TYPELIST'

export const SET_ENTITIES = 'SET_ENTITIES'

export const SET_PAGE_SIZE = 'SET_PAGE_SIZE'

export const SET_ERROR = 'SET_ERROR'
